from smartfast.exceptions import SmartfastException


class SmartfastCoreError(SmartfastException):
    pass
